apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: awesome-pet
  description: Awesome Platform Engineering Team
spec:
  type: team
  parent: awesome-project
  children: []
  members: [kirsten-gilgenberg]